### ISSUE TITLE
@Inject not working with Filter

### ISSUE THREAD

**Issue by ankuagarwal** [xvik/dropwizard-guicey-examples#5]
Hi,

I want to validate whether is user exists in the database before hitting the resources. 

1. Created a `javax.servlet.Filter` implementation

```
@javax.ws.rs.ext.Provider
public class RequestContextFilter implements Filter {
 private UserDAO userDAO;

 @Inject
  public RequestContextFilter(UserDAO userDAO) {
    this.userDAO = userDAO;
  }

 @Override
 public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse,
      FilterChain filterChain) throws IOException, ServletException {

    // Get user from header
    // Check if user exists in DB using UserDAO.find
 }
}
```
2. Added filter in the bundle

```
public class RequestContextBundle<T> implements ConfiguredBundle<T> {
  private static final String NAME = RequestContextFilter.class.getName();
  private static final String DEFAULT_PATTERN = "/*";

  @Override
  public void initialize(Bootstrap<?> bootstrap) {}

  @Override
  public void run(T t, Environment environment) {
    environment.servlets().addFilter(NAME, RequestContextFilter.class)
        .addMappingForUrlPatterns(EnumSet.of(DispatcherType.REQUEST), true, DEFAULT_PATTERN);
  }
}
```

3.  Added bundle in Application
```
  @Override
  public void initialize(final Bootstrap<InfilenConfiguration> bootstrap) {
        bootstrap.addBundle(new RequestContextFilter());
  }
```

I am getting the following error while starting the application:
```
Caused by: java.lang.NoSuchMethodException: com.xyz.RequestContextFilter.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
```

Can you please help me out.

**Comment by xvik** [comment]
Hi!

First of all, you need to register guice bundle to activate guicey:

```java
bootstrap.addBundle(GuiceBundle.builder()
      .build())
```

In guicey all extensions assumed to be guice-managed beans, so you don't need to instantiate them manually. In contrast to pure dropwizard, guicey use special [installers](http://xvik.github.io/dropwizard-guicey/5.0.0/guide/installers/) to recognize and properly register extensions for you. You only need to specify an extension class:

```java
bootstrap.addBundle(GuiceBundle.builder()
      .extensions(RequestContextFilter.class)
      .build())
```
(or extension could be found automatically via [clssapath scan](http://xvik.github.io/dropwizard-guicey/5.0.0/guide/scan/) or detected from [guice binding](http://xvik.github.io/dropwizard-guicey/5.0.0/guide/guice/module-analysis/#extensions-recognition)).

As you need to register servlet filter, you need [filters installer](http://xvik.github.io/dropwizard-guicey/5.0.0/installers/filter/), which use `@WebFilter` annotation, so your filter must be:

```java
@WebFilter("/*")
public class RequestContextFilter implements Filter {
 private UserDAO userDAO;

 @Inject
  public RequestContextFilter(UserDAO userDAO) {
    this.userDAO = userDAO;
  }

 @Override
 public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse,
      FilterChain filterChain) throws IOException, ServletException {

    // Get user from header
    // Check if user exists in DB using UserDAO.find
 }
}
```

That's all, now your filter will be installed and you should see a special log message, mentioning it.

I will add servlets and filters registration example.

Note 1: only jersey related extensions must be annotated with `@Provider` (they are installed with [jersey extensions installer](http://xvik.github.io/dropwizard-guicey/5.0.0/installers/jersey-ext/)).

Note 2: in context of guicey, it's better to use [guicey bundles](http://xvik.github.io/dropwizard-guicey/5.0.0/guide/bundles/) instead of dropwizard bundles because guicey bundles allow you to register extensions and guice modules (and some other features).

**Comment by ankuagarwal** [comment]
Hi,

I tried your approach. The `UserDAO` is initialised but the hibernate session is not yet created.
Getting following error :
`org.hibernate.HibernateException: No session currently bound to execution context`

```
bootstrap.addBundle(GuiceBundle.builder()
        .enableAutoConfig("package")
        .modules(
            new HibernateModule(hibernateBundle))
        .extensions(RequestContextFilter.class)
        .build());
 ```

```
public class HibernateModule extends AbstractModule {
  private final HibernateBundle<Configuration> hibernateBundle;
  @Override
  protected void configure() {
    bind(SessionFactory.class).toInstance(hibernateBundle.getSessionFactory());
    bind(UserDAO.class).to(UserDAOImpl.class);
}}

**Comment by xvik** [comment]
Dropwizard [hibernate bundle](https://www.dropwizard.io/en/stable/manual/hibernate.html) automatically opens hibernate session only for resources (rest), so it shouldn't be opened inside a filter.

It's not hard to manage hibernate session for guice beans using guice aop, but there is no ready to use module for that (yet). You can try to look [here](https://github.com/xvik/dropwizard-guicey/issues/42) for the solution guidance.

Or you can open the session manually inside your filter (pure hibernate). You can see [dropwizard aspect implementation](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAspect.java#L88) as reference.

**Comment by ankuagarwal** [comment]
So finally it worked:

```
 @Inject
  public RequestContextFilter(
      SessionFactory sessionFactory,
      Provider<UserDAO> userDAOProvider) {
    this.sessionFactory = sessionFactory;
    this.userServiceProvider = userServiceProvider;
 }

@Override
 public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse,
      FilterChain filterChain) throws IOException, ServletException {

    // Get user from header
    Session session = sessionFactory.openSession();
    ManagedSessionContext.bind(session);
    try {
       // Check if user exists in DB using UserDAO.find
    }
    finally {
      ManagedSessionContext.unbind(sessionFactory); 
      session.close();
    }
 }
```

**Comment by xvik** [comment]
Thank you! I added your solution [to hibernate sample](https://github.com/xvik/dropwizard-guicey-examples/tree/master/integration-hibernate#session-in-servlet-or-filter).

And also add servlets and filters [registration example](https://github.com/xvik/dropwizard-guicey-examples/tree/master/core-servlets).
